spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sg_security?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 200320abc
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 39.101.72.240
    port: 6379


mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml

